# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guitest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 480)
        mainWindow.setWindowOpacity(1.0)
        mainWindow.setAutoFillBackground(True)
        mainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 60, 121, 51))
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(19, 182, 19);\n"
"font: 14pt \"Broadway\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 60, 121, 51))
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Broadway\";\n"
"background-color: rgb(220, 64, 16);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 120, 121, 51))
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(19, 182, 19);\n"
"font: 14pt \"Broadway\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(650, 120, 121, 51))
        self.pushButton_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Broadway\";\n"
"background-color: rgb(220, 64, 16);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 20, 151, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/elquator.PNG"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 20, 211, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"Stencil\";\n"
"border-color: rgb(73, 236, 209);")
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 80, 121, 51))
        self.pushButton_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(19, 182, 19);\n"
"font: 14pt \"Broadway\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 251, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"Stencil\";\n"
"border-color: rgb(73, 236, 209);")
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 80, 121, 51))
        self.pushButton_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Broadway\";\n"
"background-color: rgb(220, 64, 16);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 741, 241))
        self.label_4.setObjectName("label_4")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "LED Test"))
        self.pushButton.setText(_translate("mainWindow", "ON"))
        self.pushButton_2.setText(_translate("mainWindow", "OFF"))
        self.pushButton_3.setText(_translate("mainWindow", "ON"))
        self.pushButton_4.setText(_translate("mainWindow", "OFF"))
        self.label_2.setText(_translate("mainWindow", "MANUAL CONTROL"))
        self.pushButton_5.setText(_translate("mainWindow", "START"))
        self.label_3.setText(_translate("mainWindow", "AUTOMATED CONTROL"))
        self.pushButton_6.setText(_translate("mainWindow", "STOP"))
        self.label_4.setText(_translate("mainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
