import RPi.GPIO as GPIO
import time

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(13,GPIO.OUT)
GPIO.setup(19,GPIO.OUT)
GPIO.setup(26,GPIO.OUT)
GPIO.setup(16,GPIO.OUT)

GPIO.output(13, False)
GPIO.output(19, True)
GPIO.output(26, True)
GPIO.output(16, True)

time.sleep(3)
GPIO.output(13, True)
GPIO.output(19, False)
GPIO.output(26, True)
GPIO.output(16, True)
time.sleep(3)
GPIO.output(13, True)
GPIO.output(19, True)
GPIO.output(26, False)
GPIO.output(16, True)
time.sleep(3)
GPIO.output(13, True)
GPIO.output(19, True)
GPIO.output(26, True)
GPIO.output(16, False)
time.sleep(3)
GPIO.output(13, True)
GPIO.output(19, True)
GPIO.output(26, True)
GPIO.output(16, True)
